name: script_convert_json_csv
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  collection: ^1.19.1
  pretty_json: ^2.0.0
  csv: ^6.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
